apiVersion: v2
name: kubefin-cost-analyzer
description: A Helm chart for kubefin-cost-analyzer
sources:
  - https://github.com/kubefin/kubefin
keywords:
  - kubefin
  - kubefin-cost-analyzer
  - kubefin-dashboard
  - FinOps
type: application
version: 0.1.0
appVersion: "0.1.2"
